package com.actionsoft.apps.fs_b2b.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-04-28T17:48:24.087+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "GetB2bDataImpl", 
                  wsdlLocation = "file:/D:/codes/GetB2bData68.xml",
                  targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/") 
public class GetB2BDataImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.fs_b2b.apps.actionsoft.com/", "GetB2bDataImpl");
    public final static QName GetB2BDataImplPort = new QName("http://ws.fs_b2b.apps.actionsoft.com/", "GetB2bDataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/codes/GetB2bData68.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetB2BDataImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/codes/GetB2bData68.xml");
        }
        WSDL_LOCATION = url;
    }

    public GetB2BDataImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetB2BDataImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetB2BDataImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetB2BDataImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetB2BDataImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetB2BDataImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetB2BDataImplPortType
     */
    @WebEndpoint(name = "GetB2bDataImplPort")
    public GetB2BDataImplPortType getGetB2BDataImplPort() {
        return super.getPort(GetB2BDataImplPort, GetB2BDataImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetB2BDataImplPortType
     */
    @WebEndpoint(name = "GetB2bDataImplPort")
    public GetB2BDataImplPortType getGetB2BDataImplPort(WebServiceFeature... features) {
        return super.getPort(GetB2BDataImplPort, GetB2BDataImplPortType.class, features);
    }

}
