
package com.actionsoft.apps.fs_b2b.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-04-28T17:48:24.027+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class GetB2BDataImplPortType_GetB2BDataImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.fs_b2b.apps.actionsoft.com/", "GetB2bDataImpl");

    private GetB2BDataImplPortType_GetB2BDataImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetB2BDataImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetB2BDataImpl ss = new GetB2BDataImpl(wsdlURL, SERVICE_NAME);
        GetB2BDataImplPortType port = ss.getGetB2BDataImplPort();  
        
        {
        System.out.println("Invoking getB2BData...");
        java.lang.String _getB2BData_webServiceNo = "BB_SYS0001";
        java.lang.String _getB2BData_params = null;
        java.lang.String _getB2BData__return = port.getB2BData(_getB2BData_webServiceNo, _getB2BData_params);
        System.out.println("getB2BData.result=" + _getB2BData__return);


        }

        System.exit(0);
    }

}
