package com.actionsoft.apps.fs_b2b.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-04-28T17:48:24.078+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/", name = "GetB2bDataImplPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GetB2BDataImplPortType {

    @WebResult(name = "return", targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/")
    @RequestWrapper(localName = "getB2bData", targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/", className = "com.actionsoft.apps.fs_b2b.ws.GetB2BData")
    @WebMethod(operationName = "getB2bData")
    @ResponseWrapper(localName = "getB2bDataResponse", targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/", className = "com.actionsoft.apps.fs_b2b.ws.GetB2BDataResponse")
    public java.lang.String getB2BData(
        @WebParam(name = "webServiceNo", targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/")
        java.lang.String webServiceNo,
        @WebParam(name = "params", targetNamespace = "http://ws.fs_b2b.apps.actionsoft.com/")
        java.lang.String params
    );
}
